# Generated by Django 4.2 on 2023-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_remove_postdash_add_on_remove_postdash_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdash',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
