# Generated by Django 4.2 on 2023-04-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_mytarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytarget',
            old_name='mytarget',
            new_name='target',
        ),
    ]
