# Generated by Django 4.2 on 2023-04-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_on',
            field=models.TextField(default='SideNote: ', max_length=255),
        ),
    ]
