# Generated by Django 4.2 on 2023-04-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_post_add_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_on',
            field=models.TextField(default='SideNote: ', max_length=50),
        ),
    ]
